### ISSUE TITLE
Return a Promise from setPano

### ISSUE THREAD

**Issue by mslemeri** [marmat/google-maps-api-addons#19]
More a feature request, but when setting the pano for a PanoMarker, a Promise would allow the user to know when the PanoMarker has been added to the DOM and can be manipulated. 

Here is my implementation using native Promises:

```js
PanoMarker.prototype.setPano = function(pano) {
	// In contrast to regular OverlayViews, we are disallowing the usage on
	// regular maps
	if (!!pano && !(pano instanceof google.maps.StreetViewPanorama)) {
		throw 'PanoMarker only works inside a StreetViewPanorama.';
	}

	// Remove the marker if it previously was on a panorama
	if (!!this.pano_) {
		this.onRemove();
	}

	// Call method from superclass
	this.setMap(pano);
	this.pano_ = pano;

	// Fire the onAdd Event manually as soon as the pano is ready
	if (!!pano) {
		if (!!this.getPanes()) {
			return new Promise(function (resolve) {
				this.onAdd();
				resolve(this);
			}.bind(this));
		} else {
			return new Promise(function (resolve) {

				// Poll for panes to become available
				var pollCallback = function() {
					if (!!this.getPanes()) {
						window.clearInterval(this.pollId_);
						this.onAdd();
						resolve(this);
					}
				};

				this.pollId_ = window.setInterval(pollCallback.bind(this), 10);
			}.bind(this));
		}
	}
}
```

While this worked for my use case, using native Promises completely eliminates IE support (even IE11 doesn't have native Promises). Therefore, we'd need to introduce an external Promise library like [bluebird](https://github.com/petkaantonov/bluebird) for cross-browser compatibility.

**Comment by marmat** [comment]
Given that the `setMap`/`setPano` methods usually don't return anything at all, I'd be fine if we return a promise on a 'best effort' basis (i.e. all browsers that support it natively will get one, everyone else continues to get nothing). I think by moving some of the code into a private method, it should be possible to do this without too much code duplication. Does that sound reasonable?

Regarding adding a dependence on an external library: I'd rather keep this library self-contained if possible.

**Comment by mslemeri** [comment]
Sounds good! I will clean up my implementation and submit a PR.

**Comment by marmat** [comment]
Thank you very much for your work!
