### ISSUE TITLE
Several markers in the same panorama with panomarker.js

### ISSUE THREAD

**Issue by SaulBurgos** [marmat/google-maps-api-addons#22]
First I want to congratulate you for this excellent library called panomarker.js.

I just want  know,  why I can not create several panomarkers in the same panorama ?

is a restriction in the library ? or a bug ? 

here an example I want to add more than one marker:  https://jsfiddle.net/sn8L7u0r/3/  , just click on the button to add several markers

I am working in an project where I need add several of these.

Thanks.

**Comment by SaulBurgos** [comment]
I found that you are using an interval function to wait until the panorama is loaded. That is the problem when I try to create another marker , the panorama is already loaded so the  "onAdd" function is called.

and the function "povToPixel_" is not assigned. The first time work because the interval wait and the function "povToPixel_" is assigned .

to fix this I only mode the order to call the functions:

      this.povToPixel_ = !!window.chrome ? PanoMarker.povToPixel3d : PanoMarker.povToPixel2d;      
     this.setPano(opts.pano || null);

**Comment by marmat** [comment]
Hi Saul,

sorry for not getting back earlier to you, your email got lost in my inbox somehow. What you're reporting was actually fixed quite a while ago (Mar 24, commit e653198). Could it be that you were working with an older version of the library?

**Comment by SaulBurgos** [comment]
thanks for your answer , that was the problem :)
