### ISSUE TITLE
Uncaught TypeError: Cannot read property 'left' of null

### ISSUE THREAD

**Issue by briscoda** [marmat/google-maps-api-addons#27]
Hello,

First, I want to say that this add on is excellent. However, I'm seeing an issue when trying to place markers based on a specific pano.

I am making a custom tour, and when the heading and pitch are 0, it seems to work alright, but when I change the heading i'm seeing the issue.

It might be helpful to say that if you click on one of the markers within the minimap is what triggers the error, or when you navigate inside of the facility.

It seems like the offset is undefined for some reason but I haven't been able to trace it down. It seems to fail a sanity check between 193 and 202.

I figured I would reach out to see if you might be able to offer any advice on this issue.  Thanks so much!

**Comment by marmat** [comment]
I don't seem to be able to reproduce the issue. What browser are you using? Is there a specific sequence of actions that I can do to trigger the error?

**Comment by briscoda** [comment]
Hi,

Thank you for following up. The issue was that when you place duplicate markers on the map each marker needs an independent anchor. It also looks like when you turn the map around to face the opposite direction, the sanity check would drop below 0 and trigger the error as well. That seemed to be consistent whether or not the markers were anchored independently of each other.

I was wondering what that sanity check was for, I replaced it with a flag to set the marker visibility to none instead of block, as it seemed like it would just trigger the marker in its opposite or inverse location on the other side of the pano.

I also added in a "secondary position" to allow multiple anchors to live on the map together. There might be a more elegant way to do this, but, if you would like I can create a pull request so you can evaluate my update.
